---
ns: ENTITY
aliases: ["0x61914209C36EFDDB"]
apiset: client
---
## GET_CARRIABLE_ENTITY_STATE

```c
// 0x61914209C36EFDDB
int GET_CARRIABLE_ENTITY_STATE(Entity entity);
```

enum eCarriableState
{
	CARRIABLE_STATE_NONE,
	CARRIABLE_STATE_TRANSITIONING_TO_HOGTIED,
	CARRIABLE_STATE_CARRIABLE_INTRO,
	CARRIABLE_STATE_CARRIABLE,
	CARRIABLE_STATE_BEING_PICKED_UP_FROM_GROUND,
	CARRIABLE_STATE_CARRIED_BY_HUMAN,
	CARRIABLE_STATE_BEING_PLACED_ON_GROUND,
	CARRIABLE_STATE_CARRIED_BY_MOUNT,
	CARRIABLE_STATE_BEING_PLACED_ON_MOUNT,
	CARRIABLE_STATE_BEING_PICKED_UP_FROM_MOUNT,
	CARRIABLE_STATE_BEING_CUT_FREE,
	CARRIABLE_STATE_BEING_PLACED_ON_GROUND_ESCAPE,
	CARRIABLE_STATE_BEING_PLACED_IN_VEHICLE
};

## Parameters
* **entity**:

## Return value