---
ns: PED
aliases: ["0x24C82EF607105FAA"]
apiset: client
---
## _SET_PED_INTERACTION_PERSONALITY

```c
// 0x24C82EF607105FAA
void _SET_PED_INTERACTION_PERSONALITY(Ped ped, Hash personality);
```

personality (script_mp_rel): NONE, AGGRESSIVE, TIMID (non-aggressive), CRIPPS, SCRIPTEDINTIMIDATION, MAGGIE, MARCEL, SCRIPTEDSALOON
personality (script_rel): AVOID, SCRIPTEDOUTLAW, TIMIDGUARDDOG, SCRIPTEDTIMIDROB, AGGRESSIVECAMPER, LAZYDOG, KIERANTIEDUP, SCRIPTEDGALA

## Parameters
* **ped**:
* **personality**: